# Generated by Django 2.2.10 on 2020-03-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200321_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
