# Generated by Django 2.2.10 on 2020-03-22 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200322_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(default=datetime.date, verbose_name='Date'),
        ),
    ]
