# Generated by Django 2.2.10 on 2020-03-22 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200322_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(default=datetime.date, verbose_name='Date'),
        ),
    ]
