# Generated by Django 2.2.10 on 2020-03-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200322_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='break_choice',
            new_name='Break_Choice',
        ),
    ]
