# Generated by Django 2.2.10 on 2020-03-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200322_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_day',
        ),
    ]
