# Generated by Django 2.2.10 on 2020-04-02 21:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_coupon'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('HotFoodItem', django.db.models.manager.Manager()),
            ],
        ),
    ]
