# Generated by Django 2.2.10 on 2020-04-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200402_2136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
