# Generated by Django 2.2.10 on 2020-04-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200402_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Break_Choice',
            new_name='break_choice',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_w_card',
            field=models.BooleanField(default=True, verbose_name='Pay with Card'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_w_cash',
            field=models.BooleanField(default=False, verbose_name='Pay with Cash at Tuck shop'),
        ),
    ]
