# Generated by Django 2.2.10 on 2020-04-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200406_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_w_card',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_w_cash',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('B', 'Credit/Debit'), ('C', 'Cash')], default='B', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='break_choice',
            field=models.CharField(choices=[('T', 'Morning Tea'), ('L', 'Lunch')], default='T', max_length=20),
        ),
    ]
