# Generated by Django 2.2.10 on 2020-04-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200406_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('B', 'Pay with Card (Credit/Debit)'), ('C', 'Pay with Cash at Tuck Shop')], default='Pay with Card (Credit/Debit)', max_length=20),
        ),
    ]
