# Generated by Django 2.2.10 on 2020-04-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200407_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('B', 'Pay with Card (Credit/Debit)'), ('C', 'Pay with Cash at Tuck Shop')], default='B', max_length=20),
        ),
    ]
