# Generated by Django 2.2.10 on 2020-06-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_variations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ItemVariation'),
        ),
    ]
