# Generated by Django 2.2.10 on 2020-06-24 04:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_dates', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_window', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CutoffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.TimeField(default=datetime.time(9, 0))),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Price (if different from base price)')),
                ('image', models.ImageField(default='media/images/no-image-available-icon-template-260nw-1036735678.jpg_xctPfVt.png', upload_to='media/images/')),
                ('slug', models.SlugField(default='', editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('net_item', models.ManyToManyField(related_name='netitems', to='core.OrderItem')),
            ],
            options={
                'verbose_name': 'Net Orders',
                'verbose_name_plural': 'Net Orders',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='item',
            name='maximum_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='item',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='variations_exist',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/images/no-image-available-icon-template-260nw-1036735678.jpg_xctPfVt.png', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orderitem', to='core.OrderItem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Pickup Date'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='itemvariation',
            unique_together={('title', 'price')},
        ),
    ]
