# Generated by Django 2.2.10 on 2020-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_orderitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
