# Generated by Django 2.2.10 on 2020-06-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
