# Generated by Django 2.2.10 on 2020-06-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
