# Generated by Django 2.2.10 on 2020-06-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itemvariation_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariation',
            name='discount_price',
        ),
    ]
