# Generated by Django 2.2.10 on 2020-06-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_itemvariation_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
