# Generated by Django 2.2.10 on 2020-06-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200609_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netorders',
            options={'verbose_name': 'Net Orders'},
        ),
    ]
