# Generated by Django 2.2.10 on 2020-06-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_itemvariation_not_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvariation',
            old_name='not_available',
            new_name='option_not_available',
        ),
    ]
