# Generated by Django 2.2.10 on 2020-06-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200611_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netorders',
            options={'verbose_name': 'Net Orders', 'verbose_name_plural': 'Net Orders'},
        ),
    ]
