# Generated by Django 2.2.10 on 2020-06-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200611_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InputDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_dates', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.AddField(
            model_name='closeddates',
            name='closed_dates',
            field=models.ManyToManyField(to='core.InputDates'),
        ),
    ]
