# Generated by Django 2.2.10 on 2020-07-21 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200625_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('slug', models.SlugField(default='')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('item_variations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ItemVariation')),
            ],
        ),
        migrations.AlterField(
            model_name='netorders',
            name='net_item',
            field=models.ManyToManyField(related_name='netitems', to='core.NetItem'),
        ),
    ]
