# Generated by Django 2.2.10 on 2020-05-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200525_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
