# Generated by Django 2.2.10 on 2020-07-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200721_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netitem',
            name='price',
        ),
    ]
