# Generated by Django 2.2.10 on 2020-07-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_netitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutofftime',
            options={'verbose_name': 'Cutoff Time', 'verbose_name_plural': 'Cutoff Time'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='variation',
            field=models.CharField(max_length=20),
        ),
    ]
