# Generated by Django 2.2.10 on 2020-07-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200723_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariation',
            name='variation',
            field=models.CharField(max_length=30),
        ),
    ]
