# Generated by Django 2.2.10 on 2020-05-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
