# Generated by Django 2.2.10 on 2020-05-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
