# Generated by Django 2.2.10 on 2020-07-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200723_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
