# Generated by Django 2.2.10 on 2020-05-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200525_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userprofile_email',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
