# Generated by Django 2.2.10 on 2020-05-25 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200525_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userprofile_email',
        ),
    ]
