# Generated by Django 2.2.10 on 2020-08-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200729_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentWindow',
        ),
    ]
