# Generated by Django 2.2.10 on 2020-05-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_userprofile_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_email',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
