# Generated by Django 2.2.13 on 2020-08-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_currentwindow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvariation',
            old_name='option_not_available',
            new_name='not_available',
        ),
    ]
