# Generated by Django 2.2.10 on 2020-05-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userprofile_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
