# Generated by Django 2.2.13 on 2020-09-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200819_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netitem',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
