# Generated by Django 2.2.13 on 2020-09-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200901_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
