# Generated by Django 2.2.10 on 2020-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200526_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
