# Generated by Django 2.2.13 on 2020-10-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
