# Generated by Django 2.2.13 on 2021-02-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='email',
        ),
    ]
